---
- import_tasks: setup.yml

- import_tasks: swapoff.yml
  when: cassandra_disable_swap

- import_tasks: configure.yml
  tags:
    - configure

- import_tasks: systemd.yml
  tags:
    - systemd

- import_tasks: repairs_backups.yml
  tags:
    - repairs
    - backups
